FROM centos:7
RUN yum -y install openssh-server
USER root
RUN yum update -y
RUN useradd admin && \
    echo "1234" | passwd admin --stdin
WORKDIR /home/admin/install
COPY jdk-8u202-linux-x64.rpm .
RUN rpm -ivh jdk-8u202-linux-x64.rpm

#Docker commands
docker run -d -p 49160:22 -p 49154:1521 --network oracle-network --name oracle -e ORACLE_ALLOW_REMOTE=true store/oracle/database-enterprise:12.2.0.1
docker run -it -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d -p 3000:3000 --network oracle-network --name server centos:latest
